variable "project_id" {}
variable "region" {}
variable "name" {}
variable "force_destroy" {}
variable "zone" {}
variable "on_delete" {}
variable "max_workers" {}
variable "template_gcs_path" {}
variable "temp_gcs_location" {}
variable "parameters" {}
variable "service_account_email" {}
variable "network_self_link" {}
variable "subnetwork_self_link" {}
variable "machine_type" {}
variable "ip_configuration" {}